name: CI Spring Boot

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    paths:
      - '**.java'
      - 'pom.xml'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    paths:
      - '**.java'
      - 'pom.xml'

jobs:
  services:
    mysql: mysql:8.0
    ports:
      - 3306:3306
    env:
      MYSQL_DATABASE: testedb
      MYSQL_ROOT_DATABASE: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  env:
    SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb
    SPRING_DATASOURCE_USERNAME: user
    SPRING_DATASOURCE_PASSWORD: pass
    SPRING_PROFILES_ACTIVE: test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: javaPackage
        run: mvn clean install -DskipTests

      - name: javaTest
        run: mvn test